<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://wrapper" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://wrapper" xmlns:intf="http://wrapper" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:portType name="UserMessageBean">

   </wsdl:portType>

   <wsdl:binding name="UserMessageBeanSoapBinding" type="impl:UserMessageBean">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

   </wsdl:binding>

   <wsdl:service name="UserMessageBeanService">

      <wsdl:port binding="impl:UserMessageBeanSoapBinding" name="UserMessageBean">

         <wsdlsoap:address location="http://localhost:8083/AirlineManagementWebService/services/UserMessageBean"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
